import 'dart:ui' show Locale;

import '../../utils/drum_locale_utils.dart';
import '../../utils/drum_numerals.dart';
import '../calendar_date.dart';
import '../drum_calendar_system.dart';
import '../jdn.dart';
import 'chinese_data.dart';

/// Traditional Chinese month names, indexed by the civil month number 1-12.
const List<String> _zhMonthNames = [
  '正月',
  '二月',
  '三月',
  '四月',
  '五月',
  '六月',
  '七月',
  '八月',
  '九月',
  '十月',
  '十一月',
  '十二月',
];

const List<String> _heavenlyStems = [
  '甲',
  '乙',
  '丙',
  '丁',
  '戊',
  '己',
  '庚',
  '辛',
  '壬',
  '癸',
];

const List<String> _earthlyBranches = [
  '子',
  '丑',
  '寅',
  '卯',
  '辰',
  '巳',
  '午',
  '未',
  '申',
  '酉',
  '戌',
  '亥',
];

const List<String> _zodiacEn = [
  'Rat',
  'Ox',
  'Tiger',
  'Rabbit',
  'Dragon',
  'Snake',
  'Horse',
  'Goat',
  'Monkey',
  'Rooster',
  'Dog',
  'Pig',
];

/// The Chinese lunisolar calendar, backed by an astronomically computed table.
///
/// Unlike the Gregorian and Hijri calendars, a Chinese year has 12 or 13
/// months: a leap year inserts a leap month (闰月) that repeats the previous
/// month's number. Month lengths (29 or 30 days) and the placement of the leap
/// month follow the new moons and solar terms at the 120 degrees east meridian,
/// so they cannot be computed by simple arithmetic and are instead looked up
/// from a vendored data table (generated by `tool/generate_chinese_data.py`
/// from the BSD licensed sxtwl engine and cross validated).
///
/// The 1 based "month" used by [decode], [encode], [daysInMonth], and the
/// picker columns is the month's position within the year (1 to 12 or 13), and
/// [CalendarDate.isLeapMonth] flags the leap month. The canonical value is, as
/// always, a Gregorian `DateTime`.
///
/// Supported range: lunar years [kChineseFirstYear] to [kChineseLastYear]. As
/// with every Chinese calendar implementation, dates far in the future are
/// predictive, since official ephemerides are published only a few years ahead.
///
/// ```dart
/// final picked = await showDrumDatePicker(
///   context: context,
///   firstDate: DateTime(2000),
///   lastDate: DateTime(2050),
///   calendar: DrumCalendarType.chinese,
///   locale: const Locale('zh'),
/// );
/// ```
class ChineseCalendarSystem extends DrumCalendarSystem {
  /// Creates the Chinese lunisolar calendar system.
  const ChineseCalendarSystem();

  static const int _firstYear = kChineseFirstYear;
  static const int _lastYear = kChineseLastYear;
  static const List<int> _starts = kChineseYearStartJdn;
  static const List<int> _codes = kChineseYearCode;

  int _leapIndex(int year) => _codes[year - _firstYear] >> 16;

  int _lengthOf(int year, int index) =>
      (_codes[year - _firstYear] & (1 << (index - 1))) != 0 ? 30 : 29;

  @override
  int monthsInYear(int year) {
    if (year < _firstYear || year > _lastYear) return 12;
    return _leapIndex(year) == 0 ? 12 : 13;
  }

  int _yearLengthDays(int year) {
    var sum = 0;
    final n = monthsInYear(year);
    for (var i = 1; i <= n; i++) {
      sum += _lengthOf(year, i);
    }
    return sum;
  }

  int _monthStartJdn(int year, int index) {
    var jdn = _starts[year - _firstYear];
    for (var i = 1; i < index; i++) {
      jdn += _lengthOf(year, i);
    }
    return jdn;
  }

  int get _minJdn => _starts.first;
  int get _maxJdn =>
      _starts.last + _yearLengthDays(_lastYear) - 1; // last day of last year

  int _clampJdn(int jdn) {
    if (jdn < _minJdn) return _minJdn;
    if (jdn > _maxJdn) return _maxJdn;
    return jdn;
  }

  @override
  CalendarDate decode(DateTime date) {
    final jdn = _clampJdn(dateToJdn(date));
    // Largest year whose first day is on or before jdn.
    var lo = 0;
    var hi = _starts.length - 1;
    while (lo < hi) {
      final mid = (lo + hi + 1) >> 1;
      if (_starts[mid] <= jdn) {
        lo = mid;
      } else {
        hi = mid - 1;
      }
    }
    final year = _firstYear + lo;
    var remaining = jdn - _starts[lo];
    var index = 1;
    while (remaining >= _lengthOf(year, index)) {
      remaining -= _lengthOf(year, index);
      index++;
    }
    return CalendarDate(year, index, remaining + 1,
        isLeapMonth: _leapIndex(year) == index);
  }

  @override
  DateTime encode(int year, int month, int day) {
    final y = year.clamp(_firstYear, _lastYear);
    final index = month.clamp(1, monthsInYear(y));
    final clampedDay = day.clamp(1, _lengthOf(y, index));
    return jdnToGregorian(_clampJdn(_monthStartJdn(y, index) + clampedDay - 1));
  }

  @override
  int daysInMonth(int year, int month) {
    if (year < _firstYear || year > _lastYear) return 30;
    return _lengthOf(year, month.clamp(1, monthsInYear(year)));
  }

  /// The civil month number (1-12) for the 1 based sequence [index] in [year].
  int _civilMonth(int year, int index) {
    final leap = _leapIndex(year);
    return (leap != 0 && index >= leap) ? index - 1 : index;
  }

  @override
  String monthName(int month,
      {required bool abbreviated, required Locale locale}) {
    // Fallback for direct callers; the picker uses [monthLabel], which is leap
    // aware. Treats [month] as a plain civil month number.
    final civil = month.clamp(1, 12);
    if (locale.languageCode == 'zh') return _zhMonthNames[civil - 1];
    return abbreviated ? '$civil' : 'Month $civil';
  }

  @override
  String monthLabel(
    int year,
    int index, {
    required bool numeric,
    required bool abbreviated,
    required Locale locale,
  }) {
    final inRange = year >= _firstYear && year <= _lastYear;
    final isLeap = inRange && _leapIndex(year) == index;
    final civil = inRange ? _civilMonth(year, index) : index;
    final localeName = DrumLocaleUtils.toIntlLocale(locale);
    final number = DrumNumerals.format(civil, localeName);

    if (locale.languageCode == 'zh') {
      final base = numeric ? number : _zhMonthNames[(civil - 1).clamp(0, 11)];
      return isLeap ? '闰$base' : base;
    }
    // English and other locales: months are numbered.
    if (numeric || abbreviated) {
      return isLeap ? 'Leap $number' : number;
    }
    return isLeap ? 'Leap Month $number' : 'Month $number';
  }

  @override
  String? yearAnnotation(int year, Locale locale) {
    if (year < _firstYear || year > _lastYear) return null;
    final stem = (year - 4) % 10;
    final branch = (year - 4) % 12;
    if (locale.languageCode == 'zh') {
      return '${_heavenlyStems[stem]}${_earthlyBranches[branch]}';
    }
    return _zodiacEn[branch];
  }

  @override
  DateTime get minSupported => jdnToGregorian(_minJdn);

  @override
  DateTime get maxSupported => jdnToGregorian(_maxJdn);

  @override
  bool isValid(int year, int month, int day) {
    if (year < _firstYear || year > _lastYear) return false;
    if (month < 1 || month > monthsInYear(year)) return false;
    if (day < 1) return false;
    return day <= _lengthOf(year, month);
  }
}
