blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/sayed3li97/material_drum_picker/discussions
    about: Ask questions and discuss ideas with the community.
